### ISSUE TITLE
Minor issue: Download link missing 

### ISSUE THREAD

**Issue by newemka** [YeonV/LedFx-Frontend-v2#21]
In the readme there is a link / download button to https://my.ledfx.app/downloads but there is no link on the Apple, Windows and Linux icons.

**Comment by YeonV** [comment]
@newemka latest version has not been built for all platforms yet. Links will appear dynamically.
I added a dropdown to choose a version: 

![image](https://user-images.githubusercontent.com/28861537/192101891-fff08de1-7eca-4969-b940-bf758c62b184.png)

![image](https://user-images.githubusercontent.com/28861537/192101816-0f9b3bdd-0e0a-416d-8390-9d0904e1c867.png)

![image](https://user-images.githubusercontent.com/28861537/192101901-bf8e5d5d-c272-40a8-a19d-e9cb162192c4.png)


in addition to the bottom section "additional downloads" where all version are in:
![image](https://user-images.githubusercontent.com/28861537/192101843-64fd0ead-fe5d-4714-91ea-058daeb93695.png)
