### ISSUE TITLE
SpotifyPro-Integration: Change current handling

### ISSUE THREAD

**Issue by YeonV** [YeonV/LedFx-Frontend-v2#24]
hello hackers!

Completely rework current implementation of the progressing seconds.

- spotify position
- [scene-trigger handling](https://github.com/YeonV/LedFx-Frontend-v2/blob/main/src/components/Integrations/Spotify/SpotifyFabPro.tsx#L65-L119)

More Infos soon.

**Comment by TheMatrixPill** [comment]
@YeonV I just made an experiment with an slighly different spotify implementation here [https://github.com/TheMatrixPill/LedFx-Frontend-v2](url). 
Is this what you imagined or am i going in the wrong direction?

**Comment by YeonV** [comment]
@TheMatrixPill 
OMMMMGGGGG broooooooooo
Reading through your code changes, its AMAZING
i need to test it later
soooo keen to see it in action
truely worth the lable `xtream  hacker`

**Comment by TheMatrixPill** [comment]
#28
