### ISSUE TITLE
Starting with error code 48

### ISSUE THREAD

**Issue by Doublefire-Chen** [YeonV/LedFx-Frontend-v2#31]
Just shown as the attachment, any suggestions?
![Screen Shot 2022-10-21 at 16 14 54](https://user-images.githubusercontent.com/72138342/197148408-f59b9337-e31d-4693-8cfe-1f15076293f6.png)
Device: MacBook Pro (intel chip)
Software version: 
![Screen Shot 2022-10-21 at 16 19 25](https://user-images.githubusercontent.com/72138342/197148329-1db1831b-b3e7-4834-9e19-3b6322b0650d.png)
Both Core version and CC version 2.0.0-beta50 are tried, same problem.
How to reappear:
Install the 2.0.0-beta50 version software for Mac with intel chip([LedFx_CC_v2.0.50--mac-i386.app.zip](https://github.com/YeonV/LedFx-Frontend-v2/releases/download/2.0.0-beta50/LedFx_CC_v2.0.50--mac-i386.app.zip) or [LedFx_client_v2.0.50--mac-i386.zip](https://github.com/YeonV/LedFx-Frontend-v2/releases/download/2.0.0-beta50/LedFx_client_v2.0.50--mac-i386.zip)), add your wled strip, and start it. You will find nothing changed with your leds, and appears error code 48.
I'd be appreciated if anyone could help me. Thanks in advance.

**Comment by YeonV** [comment]
Hi @Doublefire-Chen 
Can you try to delete your config file and use the newer version:
https://github.com/YeonV/LedFx-Builds/releases/tag/v2.0.51

Never had that issue before, but maybe we can solve it together

**Comment by Doublefire-Chen** [comment]
> Hi @Doublefire-Chen Can you try to delete your config file and use the newer version: https://github.com/YeonV/LedFx-Builds/releases/tag/v2.0.51
> 
> Never had that issue before, but maybe we can solve it together

Have tried this just now, when I restart my mac and open the software, though no error code, the wled shut down and has no response, and when I reopen the software, the error code reappear with 48. Quite strange. I have tried another virtual audio input software, didn't work too.

**Comment by Doublefire-Chen** [comment]
Forget to mention, I used to use ledfx original core(Terminal version), the same issue, first launch, nothing wrong. When restart, it will also show error code 48, but it didn't influence the use, so I did't care about it. But with this software, it can't use with this error.

**Comment by Doublefire-Chen** [comment]
> Forget to mention, I used to use ledfx original core(Terminal version), the same issue, first launch, nothing wrong. When restart, it will also show error code 48, but it didn't influence the use, so I did't care about it. But with this software, it can't use with this error.

When I meet this error code in this software, I find my old ledfx can't work too.
related log:
```[ERROR   ] aiohttp.server                 : Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/ledfx/api/__init__.py", line 26, in handler
    return await method(
  File "/usr/local/lib/python3.10/site-packages/ledfx/api/audio_devices.py", line 29, in get
    audio_devices["active_device_index"] = audio_config["device_index"]
KeyError: 'device_index'```
It seems can't launch the audio device.

**Comment by Doublefire-Chen** [comment]
Now I am using this version.([LedFx_CC-v2.0.51--mac-x64.dmg](https://github.com/YeonV/LedFx-Builds/releases/download/v2.0.51/LedFx_CC-v2.0.51--mac-x64.dmg) )
Problem solved by remove the old ledfx from [LedFx](https://github.com/LedFx/LedFx)(the original core version, which you also a developer, hh). It seems the two can't exist in a mac at the same time.
# Detailed steps
1. ```pip install pip-autoremove```
2. ```pip-autoremove ledfx```
3. restart your mac
Only in this way can we delete the old ledfx compeletely.

**Comment by Doublefire-Chen** [comment]
One more thing, you need restart your mac if you want to restart ledfx CC after close it as the 5568 port won't shut down automatically when you close the software, else you will receive the error code 48 and can't use it.
