### ISSUE TITLE
Documentation on Virtuals and Segments 

### ISSUE THREAD

**Issue by Curclamas** [YeonV/LedFx-Frontend-v2#39]
Is there any documentation on Virtuals in LedFX? I am especially interested in the Mapping documentation (span vs copy).

I have a setup with 12 segments, but don't want to run different effects on all of them. Also I don't want a single effect to span multiple strips, since this looks a bit strange (esp. Marching or Fire). 

I hoped there is a setting to help me just copy effects over.

**Comment by YeonV** [comment]
@Curclamas Hi. Sadly there is almost no documentation. The only "helping" thing would be our In-App-Tours (accessable via the top-right-menu).

I think ledfx can do what you want: "copy"

## Explainations:
### copy: 
every segment will recieve the same effect, set on the virtual.

### span:
all segments are grouped together as a long strip.

### CopyTo (streamTo)
if you activate Settings->UI->Expert->CopyTo (or StreamTo)
you will have another Card on your Device-View. there you can add as many devices/virtuals as you want and you have a button to copy the effect of the currect device to all selected ones.

Maybe you can contribute better texts/images for our tour, to make it more understandable especially for new users.

Feel free to join our discord:
https://discord.gg/NnGuYaJk
