### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by ElectroYModz** [YeonV/LedFx-Frontend-v2#45]
ccess to XMLHttpRequest at 'http://localhost:8888/api/scenes' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by YeonV** [comment]
ledfx backend should support Cors already. which versions are you running?

**Comment by ElectroYModz** [comment]
the latest version

**Comment by YeonV** [comment]
Are you running it from source? localhost:3000 should only be the origin, if you are developing.
apart from, that there should be no  CORS issue, are you sure, you are using the a version from here?
https://github.com/YeonV/LedFx-Builds/releases
