### ISSUE TITLE
Feature Request, clickable number fields for virtuals config

### ISSUE THREAD

**Issue by JoshuaParra11** [YeonV/LedFx-Frontend-v2#52]
Hi, I'm college sophomore student currently taking a FOSS/FLOSS class in which an assignment is to make a contribution to a project and I was directed to YeonV, I thought I could contribute by adding this feature which makes it easier to input specific values. Original request here https://github.com/LedFx/LedFx/issues/423.

**Comment by YeonV** [comment]
@JoshuaParra11 That is amazing! Welcome onboard.
Looking forward to your contribution, please ask if you need any help

**Comment by YeonV** [comment]
will be included in 2.0.92

![image](https://github.com/YeonV/LedFx-Frontend-v2/assets/28861537/e1930b7b-a32e-4877-ac5e-a8cdf548411f)
