### ISSUE TITLE
Frequency setting fails to set low frequency. 

### ISSUE THREAD

**Issue by BigSullyOS** [YeonV/LedFx-Frontend-v2#55]
Backend
version:
commit:
config_version: 2.2.0

Frontend
version: 2.0.72
commit: [b8fd18b](https://github.com/YeonV/LedFx-Frontend-v2/commit/b8fd18bbd26527605d133de7dbaf65eb10dc3ec0)
config_version: 9

### Issue
In expert mode with frequencies turned on.

In the device setting, the low frequency setting will not stay set and resets to 20Hz.

**Comment by YeonV** [comment]
https://github.com/LedFx/LedFx/pull/478

will be included in the next release
