### ISSUE TITLE
Fixing Code for the transpose Function - Type Error (minor issue)

### ISSUE THREAD

**Issue by Lrs-mtos** [YeonV/LedFx-Frontend-v2#56]
Currently, the code in the transpose function is causing a type error that needs to be fixed to ensure code accuracy and safety. The specific error is:
~~~ python
 Type 'any' is not assignable to type 'never'.  
~~~
I am planning to send a PR to help solving this.

**Comment by YeonV** [comment]
https://github.com/YeonV/LedFx-Frontend-v2/pull/57
