### ISSUE TITLE
website footer?

### ISSUE THREAD

**Issue by ChinChillaSPb** [YeonV/LedFx-Frontend-v2#58]
on your website (https://download.ledfx.app/) there is a strange string at footer block - hacked by blade...

forgive me if im too paranoid

**Comment by YeonV** [comment]
> on your website (https://download.ledfx.app/) there is a strange string at footer block - hacked by blade...
> 
> forgive me if im too paranoid

its a sign of quality ;)

never the less, changed for the scary ones
