### ISSUE TITLE
Graphs are not working on WLED devices?

### ISSUE THREAD

**Issue by Nikey** [YeonV/LedFx-Frontend-v2#7]
Hey,
first of all great project! Love your UI!
But I have a problem with the graphs are not coming up for my WLED devices (see the screenshot)...
Tried with latest Firefox and Chrome browser.
![firefox_X2jfgvHwaE](https://user-images.githubusercontent.com/3626269/153296061-e1b0ee33-dbe1-41ca-8b53-850ff9da9a5e.png)

**Comment by Sandemonium** [comment]
I have the same issue when using WLED as the type.  I have to use e131 as the type and then it works.

**Comment by YeonV** [comment]
@Nikey @Sandemonium 
ohhh just saw this. Did not know people know my repo-
will fix this in the next release
